try {
  alert("An exception will occur");
} catch (e) {
  alert("Exception occured");
} finally {
  alert("This line always executes");
}
