try {
  alert("Thi is code inside the try clause");
  alert('This code won't work');
} catch (exception) {
  alert("The error is " + exception.message);
}
